//! Local QR-code PNG generation for connection keys.
//!
//! Every platform needs to show a scannable QR code for an `aivpn://...`
//! connection key. Rather than depending on a network call or a web-panel
//! dependency, this renders the QR code entirely inside the shared client
//! core so mobile/desktop FFI callers (`P2.3`) get PNG bytes back directly.

use image::Luma;
use qrcode::QrCode;

/// Default pixel size (in device px) of a single QR module (a.k.a. "dot").
/// 8px/module keeps the code comfortably scannable by phone cameras while
/// staying small (a typical `aivpn://` key renders at version ~6-10, i.e.
/// roughly 40-60 modules per side plus the 4-module quiet zone).
const DEFAULT_MODULE_PX: u32 = 8;

/// Render `text` as a QR code and encode it as PNG bytes, using the default
/// module scale ([`DEFAULT_MODULE_PX`]) and the crate default 4-module quiet
/// zone.
pub fn png_for(text: &str) -> anyhow::Result<Vec<u8>> {
    png_for_scaled(text, DEFAULT_MODULE_PX)
}

/// Render `text` as a QR code and encode it as PNG bytes, scaling each QR
/// module to `module_px` device pixels.
///
/// Returns an error (never panics) if `text` is empty or exceeds the QR
/// code's maximum data capacity.
pub fn png_for_scaled(text: &str, module_px: u32) -> anyhow::Result<Vec<u8>> {
    if text.is_empty() {
        anyhow::bail!("qr: refusing to encode an empty string");
    }
    if module_px == 0 {
        anyhow::bail!("qr: module_px must be non-zero");
    }

    let code = QrCode::new(text.as_bytes())
        .map_err(|e| anyhow::anyhow!("qr: failed to encode connection key: {e:?}"))?;

    let image = code
        .render::<Luma<u8>>()
        .module_dimensions(module_px, module_px)
        .build();

    let mut png_bytes = Vec::new();
    image::DynamicImage::ImageLuma8(image)
        .write_to(
            &mut std::io::Cursor::new(&mut png_bytes),
            image::ImageFormat::Png,
        )
        .map_err(|e| anyhow::anyhow!("qr: failed to encode PNG: {e}"))?;

    Ok(png_bytes)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// PNG files always start with this fixed 8-byte magic signature.
    const PNG_MAGIC: &[u8; 8] = b"\x89PNG\r\n\x1a\n";

    #[test]
    fn png_for_returns_valid_png_bytes() {
        let bytes = png_for("aivpn://AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=example")
            .expect("png_for should succeed for a normal connection key");
        assert!(!bytes.is_empty());
        assert!(
            bytes.starts_with(PNG_MAGIC),
            "output does not start with the PNG magic signature"
        );
    }

    #[test]
    fn png_for_decodes_as_a_valid_image_with_positive_dimensions() {
        let bytes = png_for("aivpn://connection-key-roundtrip-test").unwrap();
        let img =
            image::load_from_memory(&bytes).expect("generated bytes must decode as a valid PNG");
        assert!(img.width() > 0);
        assert!(img.height() > 0);
    }

    #[test]
    fn png_for_scaled_changes_output_dimensions() {
        let small = png_for_scaled("aivpn://scale-test", 2).unwrap();
        let large = png_for_scaled("aivpn://scale-test", 12).unwrap();

        let small_img = image::load_from_memory(&small).unwrap();
        let large_img = image::load_from_memory(&large).unwrap();

        assert!(large_img.width() > small_img.width());
        assert!(large_img.height() > small_img.height());
    }

    #[test]
    fn png_for_empty_string_errors_gracefully() {
        let result = png_for("");
        assert!(result.is_err(), "empty input must error, not panic");
    }

    #[test]
    fn png_for_zero_module_px_errors_gracefully() {
        let result = png_for_scaled("aivpn://x", 0);
        assert!(result.is_err(), "module_px=0 must error, not panic");
    }

    #[test]
    fn png_for_very_long_string_does_not_panic() {
        // QR codes (even at the largest version, with the lowest error
        // correction level) can hold at most a few thousand bytes. This
        // comfortably exceeds that capacity and must return Err, not panic.
        let huge = "a".repeat(50_000);
        let result = png_for(&huge);
        assert!(
            result.is_err(),
            "oversized input must error gracefully instead of panicking"
        );
    }

    #[test]
    fn png_for_typical_connection_key_length_succeeds() {
        // A realistic aivpn:// connection key: base64 PSK + host + params.
        let key = format!(
            "aivpn://{}@vpn.example.com:44300?name=phone&mask=webrtc_vk_teams_v1",
            "A".repeat(44)
        );
        let bytes = png_for(&key).expect("realistic connection keys must encode successfully");
        assert!(bytes.starts_with(PNG_MAGIC));
    }
}
